name: "Pull Request Feedback"
description: ""
author: "Exit0 Team"
inputs:
  capture_stdout:
    description: "Whether to capture and return the standard output of the executed commands."
    required: false
    default: "true"
  school-checks-repo:
    description: "Repository containing the school checks and tests (e.g., exit0-io/YoloServiceSchoolChecks)"
    required: true



outputs:
  stdout:
    description: "Standard output of the executed commands when capture_stdout is enabled."
    value: ${{ steps.entrypoint.outputs.stdout }}

runs:
  using: "composite"
  steps:
    - name: Check Action Version
      shell: bash
      run: |
        echo "reviewing..."

branding:
  icon: "award"
  color: "green"
